## Read/write functions for the findings table
'''
Each of the .execute() calls runs their own transaction.
Re-running ingestions uses the upsert functions which avoids duplicate findings 
and updates the existing finding with the latest data.
'''
from typing import Optional
from uuid import UUID
from supabase import Client
from schemas.finding import Finding
from postgrest.exceptions import APIError # DB error handling as API


_DB_MANAGED_COLUMNS = {"finding_id", "created_at", "updated_at"} # auto generated by DB
_NATURAL_KEY = "source_scanner,scan_id,source_finding_id" # Same finding / Unique constraint

## Defining the custom exceptions for DB errors (Named error types)
class FindingDBError(Exception):
    """Base class for all finding database errors"""
class FindingInsertError(FindingDBError):
    """Raised when inserting into the finding table fails"""

class FindingUpsertError(FindingDBError):
    """Raised when upserting into the finding table fails"""

class FindingNotFoundError(FindingDBError):
    """Raised when a finding is not found in the database"""


# Converts Python Finding object into JSON for supabase (returns dict)
def _serialise_for_insert(finding: Finding) -> dict:
    return finding.model_dump(
        exclude = _DB_MANAGED_COLUMNS,
        mode="json" 
    )

# Creates readable label for error message purposes to identify the finding (returns string)
def _finding_identity(finding: Finding):
    return (
        "scanner=" + str (finding.source_scanner) + "," +
        "scan_id=" + str (finding.scan_id) + "," +
        "source_finding_id=" + str (finding.source_finding_id)
    )

# Writing functions

# Inserts a finding into the database and returns the generated finding_id (returns UUID)
# Fails on duplicate and uses upsert_finding for re-run ingestions
def insert_finding(supabase: Client, finding: Finding):
    # Converts this single Finding object into JSON/dict so that Supabase can insert it
    payload = _serialise_for_insert(finding)
    try:
        response = supabase.table("findings").insert(payload).execute()
    except APIError as e:
        raise FindingInsertError(
            f"Insert failed for finding ({_finding_identity(finding)}): {e.message}"
        ) from e

    if not response.data:
        raise FindingInsertError(
            f"Insert returned no data for finding ({_finding_identity(finding)})"
        )
    return UUID(response.data[0]["finding_id"])

# Inserts multiple findings into the database and returns a list of generated finding_ids (returns list[UUID])
# Raises FIndingInsertError if the insert fails
def insert_findings_bulk(supabase: Client, findings: list[Finding]):
    if not findings:
        return []
    
    # loops through all Finding objects, converts each to a JSON/dict, stored in a list to be bulk inserted into Supabase
    payload = [_serialise_for_insert(f) for f in findings]
    try:
        response = supabase.table("findings").insert(payload).execute()
    except APIError as e:
        raise FindingInsertError(
            f"Bulk insert failed for {len(findings)} findings: {e.message}"
        ) from e
    if not response.data:
        raise FindingInsertError(
            f"Bulk insert returned no data for {len(findings)} findings"
        )
    return [UUID(row["finding_id"]) for row in response.data]

# Updates an existing finding based on natural key instead of duplicating it (Peforms an upsert)
# Returns the finding_id of the upserted finding (returns UUID)
def upsert_finding(supabase: Client, finding: Finding):
    payload = _serialise_for_insert(finding)

    try:
        response = (
            supabase.table("findings"). 
            upsert(payload, on_conflict = _NATURAL_KEY).execute()
        )
    except APIError as e:
        raise FindingUpsertError(
            f"Upsert failed for finding ({_finding_identity(finding)}): {e.message}"
        ) from e

    if not response.data:
        raise FindingUpsertError(
            f"Upsert returned no data for finding ({_finding_identity(finding)})"
        )
    return UUID(response.data[0]["finding_id"])

# Updates multiple findings based on natural key instead of duplicating them
def upsert_findings_bulk(supabase: Client, findings: list[Finding]):
    if not findings:
        return []

    payload = [_serialise_for_insert(f) for f in findings]
    try:
        response = (
            supabase.table("findings")
            .upsert(payload, on_conflict = _NATURAL_KEY).execute()
        )
    except APIError as e:
        raise FindingUpsertError(
            f"Bulk upsert failed for {len(findings)} findings: {e.message}"
        ) from e

    if not response.data:
        raise FindingUpsertError(
            f"Bulk upsert returned no data for {len(findings)} findings"
        )
    return [UUID(row["finding_id"]) for row in response.data]

# Reading functions

# Fetches one finding by its finding_id, returns None if not found (returns Optional[Finding])
# Raises FindingDBError if the query fails (e.g. DB connection issue)
def get_finding(supabase: Client, finding_id: UUID) -> Optional[Finding]:
    
    try: 
        response = supabase.table("findings").select("*").eq("finding_id", str(finding_id)).limit(1).execute()
    except APIError as e:
        raise FindingDBError(
            f"Failed to fetch finding ({finding_id}): {e.message}"
        ) from e
    
    if not response.data:
        return None
    return Finding(**response.data[0])

# Fetches findings with optional filters for scanner, host, and severity, ordered by created_at desc, 
# limited to specified num of results (default is 100) & (Returns list[Finding])
# Raises FindingDBError if the query fails (e.g. DB connection issue)
def list_findings(
    supabase: Client,
    scanner: Optional[str] = None,
    host: Optional[str] = None,
    severity: Optional[str] = None,
    scan_id: Optional[str] = None,
    limit: int = 100, # only 100 rows produced
):
    query = supabase.table("findings").select("*")
    
    if scanner is not None:
        query = query.eq("source_scanner", scanner)
    if host is not None:
        query = query.eq("target_host", host)
    if severity is not None:
        query = query.eq("severity_level", severity)
    if scan_id is not None:
        query = query.eq("scan_id", scan_id)
    
    try:
        response = query.order("created_at", desc=True).limit(limit).execute()
    except APIError as e:
        raise FindingDBError(f"Failed to list findings: {e.message}"
        ) from e
    return [Finding(**row) for row in response.data]