## Read/write functions for the findings table
from typing import Optional
from uuid import UUID
from supabase import Client
from schemas.finding import Finding

_DB_MANAGED_COLUMNS = {"finding_id", "created_at", "updated_at"} # auto generated by DB

# Converts Python Finding object into JSON for supabase
def _serialise_for_insert(finding: Finding) -> dict:
    return finding.model_dump(
        exclude = _DB_MANAGED_COLUMNS,
        mode="json" 
    )

# Inserts a finding into the database and returns the generated finding_id
def insert_finding(supabase: Client, finding: Finding) -> UUID:
    payload = _serialise_for_insert(finding)
    response = supabase.table("findings").insert(payload).execute()

    if not response.data:
        raise RuntimeError(f"Failed to insert finding: {response}")
    return UUID(response.data[0]["finding_id"])

# Inserts multiple findings into the database and returns a list of generated finding_ids
def insert_findings_bulk(supabase: Client, findings: list[Finding]) -> list[UUID]:
    if not findings:
        return []
    
    payload = [_serialise_for_insert(f) for f in findings]
    response = supabase.table("findings").insert(payload).execute()

    if not response.data:
        raise RuntimeError(f"Failed to insert finding: {response}")
    return [UUID(row["finding_id"]) for row in response.data]

# Fetches one finding by its finding_id, returns None if not found
def get_finding(supabase: Client, finding_id: UUID) -> Optional[Finding]:
    response = supabase.table("findings").select("*").eq("finding_id", str(finding_id)).limit(1).execute()
    if not response.data:
        return None
    return Finding(**response.data[0])

def list_findings(
    supabase: Client,
    scanner: Optional[str] = None,
    host: Optional[str] = None,
    severity: Optional[str] = None,
    limit: int = 100, # only 100 rows produced
) -> list[Finding]:
    query = supabase.table("findings").select("*")
    
    if scanner is not None:
        query = query.eq("source_scanner", scanner)
    if host is not None:
        query = query.eq("target_host", host)
    if severity is not None:
        query = query.eq("severity_level", severity)
    
    response = query.order("created_at", desc=True).limit(limit).execute()
    return [Finding(**row) for row in response.data]